### PR TITLE
Tailwind migration - last part

### PR DESCRIPTION
**Pull request by PejmanG**
The migration to tailwind is complete

Removed styled components and it's related stylings from the project

Added a useEffect to _app.tsx for handling theme switch

There are some visual bugs that, as soon as I fix them, the PR will be ready for merge.

### CODE REVIEW

**Comment by kyh** [comment]
Thank you so much, great to see the progress

**Comment by PejmanG** [comment]
Every page that I could check was tested and fixed, and to make the migrated components look more similar to the original, I gave every bordered component the `rounded-wavy` class

I couldn't make an account to test the authed components; Are there any accounts in the dev DB so I can test those?

**Comment by kyh** [comment]
you can create an account by going to `/auth/signup` and register

**Comment by PejmanG** [comment]
I went through all the routes that were behind authentication and fixed the visual bugs that I could see

The test process was me checking if things visually matched the live version, but there were some routes or functionality I couldn't verify

Things that I couldn't check are:

In the `/packs/[packId]/edit` route I could only make sure the empty pack editor looked similar; In both live and local versions, I couldn't  add new scenes, and when I tried using the CSV import, nothing happened but a 500 error in the console (In both versions)
The `Add New Scene` button on that page results in this error :
`Cannot destructure property 'data' of '(intermediate value)' as it is undefined.`

The `/packs/category/[tagSlug]` route doesn't open and results in `TypeError: Cannot convert undefined or null to object` error caused by the `PackCategory.tsx` file

**Pull request merged**
